### ISSUE TITLE
bug: no license specified for the code

### ISSUE THREAD

**Issue by dmhowcroft** [madcpt/OpenDialKG#1]
There's a license listed for the dataset, but there's nothing specified for the code itself.

Could you please specify one to make it easier for others to use your code? Perhaps [Apache 2.0](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)), [MIT](https://tldrlegal.com/license/mit-license), or [GPL](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3))?

**Comment by madcpt** [comment]
Thanks for your suggestion! I have uploaded a LICENSE for the code.

Actually, this project was not finished due to some issues with the OpenDialKG dataset (the released dataset is incomplete). Still, I would be happy if any part of my code would be useful.

**Comment by dmhowcroft** [comment]
Ah, good to know! Thanks for the update :)

One more thing about the license, though: it seems that [Creative Commons advises against using their licenses for software](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software).

**Comment by madcpt** [comment]
Sorry for the confusion! I have changed the license to GPL, and I'm just getting to learn these things :)
